/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car/scene.gltf 
Author: doncha_magoso (https://sketchfab.com/doncha_magoso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-car-low-poly-ec5526b7f8d34e109b8b5e81bab750e5
Title: Toy Car Low poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/car/scene.gltf')
  return (
    <group {...props} dispose={null} scale={0.2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Black_outline} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Coche_Pintura3} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Coche_blanco} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Coche_gris01} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Coche_gris02} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Coche_negro} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Coche_rojo} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/car/scene.gltf')
