/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/city2/scene.gltf 
Author: Hassan (https://sketchfab.com/H_a_s_s_a_n)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/city-low-poly-free-696551b01630424cafdf85ccb2bed14d
Title: City Low Poly Free
*/

import React, { useRef,useEffect } from 'react'
import { Environment, useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
export function City(props) {
  const { nodes, materials } = useGLTF('/models/city2/scene.gltf')
  const city = useRef();
  return (
    <RigidBody type="fixed" position={[0, 0, 0]} colliders="hull" >
      <Environment preset="city" background={false}/>
    <group {...props} dispose={null} ref={city} receiveShadow>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_2} position={[0, 68.364, 0]} scale={[1, 0.033, 1]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} position={[0, 66.428, 0]} scale={[1, 0.032, 1]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_5} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.material_2} position={[0, 88.122, 0]} scale={[1, 0.035, 1]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_6} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.material_2} position={[0, 74.85, 0]} scale={[1, 0.042, 1]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material_7} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material_2} position={[0, 42.014, 0]} scale={[1, 0.081, 1]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material_8} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_2} position={[0, 51.96, 0]} scale={[1, 0.063, 1]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material_9} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[0, 19.506, 0]} scale={[1, 0.133, 1]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.material_10} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material_2} position={[0, 54.459, 0]} scale={[1, 0.068, 1]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.material_11} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.material_2} position={[0, 73.044, 0]} scale={[1, 0.056, 1]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.material_12} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.material_2} position={[0, 36.706, 0]} scale={[1, 0.087, 1]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material_13} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.material_2} position={[0, 22.362, 0]} scale={[1, 0.053, 1]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.material_14} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.material_2} position={[0, 87.521, 0]} scale={[1, 0.078, 1]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.material_15} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.material_2} position={[0, 58.62, 0]} scale={[1, 0.135, 1]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.material_16} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.material_17} position={[0, 0.803, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.material_2} position={[0, 25.33, 0]} scale={[1, 0.117, 1]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.material_18} position={[0, 1.112, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.material_2} position={[-0.292, 60.998, -0.047]} scale={[1, 0.042, 1]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.material_19} position={[0, 0, 0.967]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.material_2} position={[-0.621, 77.976, 0.953]} scale={[1, 0.046, 1]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.material_20} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.material_2} position={[0, 44.789, 0]} scale={[1, 0.074, 1]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.material_21} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.material_2} position={[-0.191, 66.747, 0.028]} scale={[1, 0.028, 1]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.material_22} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.material_2} position={[0, 80.805, 0]} scale={[1, 0.041, 1]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.material_16} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.material_2} position={[0, 33.97, 0]} scale={[1, 0.14, 1]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.material_23} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.material_2} position={[0, 59.883, 0]} scale={[1, 0.117, 1]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.material_24} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.material_2} position={[0, 63.06, 0]} scale={[1, 0.089, 1]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.material_25} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.material_2} position={[0, 51.808, 0]} scale={[1, 0.05, 1]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.material_26} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.material_2} position={[0, 62.63, 0]} scale={[1, 0.063, 1]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.material_27} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.material_2} position={[0, 73.694, 0]} scale={[1, 0.05, 1]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.material_28} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.material_2} position={[0, 88.547, 0]} scale={[1, 0.116, 1]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.material_29} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.material_2} position={[0, 84.185, 0]} scale={[1, 0.045, 1]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.material_30} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.material_2} position={[0.357, 110.953, 0.478]} scale={[1.004, 0.024, 1.004]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.material_23} rotation={[0.002, 0, 0]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.material_2} position={[0, 76.276, 0]} rotation={[0.002, 0, -Math.PI]} scale={[-1, 0.046, 1.002]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.material_31} position={[0, 0.351, 0]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.material_2} position={[0.126, 55.214, 0.029]} scale={[1, 0.028, 1]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.material_32} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.material_2} position={[-1.297, 33.114, -1.031]} rotation={[0, -0.011, 0]} scale={[1, 0.124, 1]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.material_33} position={[36.603, 0, 0]} scale={[1.624, 0.999, 0.999]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.material_2} position={[36.603, 57.612, 0]} scale={[1.624, 0.025, 0.999]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.material_34} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.material_2} position={[0, 36.842, 0]} scale={[1, 0.071, 1]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.material_35} position={[4.052, 0.951, 0]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.material_2} position={[4.052, 36.448, 0]} scale={[1, 0.11, 1]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.material_36} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.material_2} position={[0, 35.564, 0]} scale={[1, 0.088, 1]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.material_37} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.material_2} position={[0, 54.257, 0]} scale={[1, 0.023, 1]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.material_35} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.material_2} position={[0, 70.93, 0]} scale={[1, 0.056, 1]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.material_38} position={[0, 1.248, 0]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.material_2} position={[0, 66.711, 0]} scale={[1, 0.07, 1]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.material_39} position={[0, 0.915, 0]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.material_2} position={[0, 31.714, 0]} scale={[1, 0.095, 1]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.material_40} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.material_2} position={[0, 72.224, 0]} scale={[1, 0.069, 1]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.material_41} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.material_41} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.material_41} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.material_42} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.material_42} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.material_43} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_214.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_216.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_218.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_220.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_222.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_224.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_226.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_228.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_230.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_232.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_234.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_236.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_238.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_240.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_242.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_244.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_246.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_248.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_250.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_252.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_256.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_258.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_260.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_262.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_264.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_266.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_268.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_270.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_272.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_274.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_276.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_278.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_280.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_282.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_284.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_286.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_288.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_290.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_292.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_294.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_296.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_298.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_300.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_302.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_304.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_306.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_308.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_310.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_312.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_314.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_316.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_318.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_320.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_322.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_324.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_326.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_328.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_330.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_332.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_334.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_336.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_338.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_340.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_342.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_344.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_346.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_348.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_350.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_352.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_354.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_356.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_358.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_360.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_362.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_364.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_366.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_368.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_370.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_372.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_374.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_376.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_378.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_380.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_382.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_384.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_386.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_388.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_390.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_392.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_394.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_396.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_398.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_400.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_402.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_404.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_406.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_408.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_410.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_412.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_414.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_416.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_418.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_420.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_422.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_424.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_426.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_428.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_430.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_432.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_434.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_436.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_438.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_440.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_442.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_444.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_446.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_448.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_450.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_452.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_454.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_456.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_458.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_460.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_462.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_464.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_466.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_468.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_470.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_472.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_474.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_476.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_478.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_480.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_482.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_484.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_486.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_488.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_490.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_492.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_494.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_496.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_498.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_500.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_502.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_504.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_506.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_508.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_510.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_512.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_514.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_516.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_518.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_520.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_522.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_524.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_526.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_528.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_530.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_532.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_534.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_536.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_538.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_540.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_542.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_544.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_546.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_548.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_550.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_552.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_554.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_556.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_558.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_560.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_562.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_564.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_566.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_568.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_570.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_572.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_574.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_576.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_578.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_580.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_582.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_584.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_586.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_588.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_590.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_592.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_594.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_596.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_598.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_600.geometry} material={materials.material_44} />
      <mesh geometry={nodes.Object_602.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_604.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_606.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_608.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_610.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_612.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_614.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_616.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_618.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_620.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_622.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_624.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_626.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_628.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_630.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_632.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_634.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_636.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_638.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_640.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_642.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_644.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_646.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_648.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_650.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_652.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_654.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_656.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_658.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_660.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_662.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_664.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_666.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_668.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_670.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_672.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_674.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_676.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_678.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_680.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_682.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_684.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_686.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_688.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_690.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_692.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_694.geometry} material={materials.material_2} position={[0, -0.183, 0]} scale={[1, 1.322, 1]} />
      <mesh geometry={nodes.Object_696.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_698.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_700.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_702.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_704.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_706.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_708.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_710.geometry} material={materials.material_2} />
    </group>
    </RigidBody>
  )
}

useGLTF.preload('/models/city2/scene.gltf')
