/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bmw/scene.gltf 
Author: rifdanzz (https://sketchfab.com/rifdanzz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-320i-e90-low-polly-28f0bc2f0083417a8e521150529034d6
Title: BMW 320i E90 Low Polly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-68.955, 17.091, 139.239]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={31.842}>
        <mesh geometry={nodes.Circle002_velg_0.geometry} material={materials.velg} />
        <mesh geometry={nodes.Circle002_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle002_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[76.42, 17.104, 139.234]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={31.842}>
        <mesh geometry={nodes.Circle003_velg_0.geometry} material={materials.velg} />
        <mesh geometry={nodes.Circle003_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle003_Material009_0.geometry} material={materials['Material.009']} />
      </group>
      <group position={[67.205, 17.091, -138.696]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={31.842}>
        <mesh geometry={nodes.Circle004_velg_0.geometry} material={materials.velg} />
        <mesh geometry={nodes.Circle004_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle004_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-68.955, 17.091, -138.696]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={31.842}>
        <mesh geometry={nodes.Circle005_velg_0.geometry} material={materials.velg} />
        <mesh geometry={nodes.Circle005_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle005_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635}>
        <mesh geometry={nodes.Plane009_Material003_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Plane009_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635}>
        <mesh geometry={nodes.Plane010_Material003_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Plane010_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635}>
        <mesh geometry={nodes.Plane015_glass_0.geometry} material={materials.glass} />
        <mesh geometry={nodes.Plane015_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Circle_Material005_0.geometry} material={materials['Material.005']} position={[0, 63.529, 191.14]} rotation={[-1.21, 0, 0]} scale={4.629} />
      <mesh geometry={nodes.Circle001_Material005_0.geometry} material={materials['Material.005']} position={[0, 79.076, -229.819]} rotation={[3.05, 0, Math.PI]} scale={3.374} />
      <mesh geometry={nodes.Circle006_Material001_0.geometry} material={materials['Material.001']} position={[36.123, 13.063, -233.381]} scale={3.319} />
      <mesh geometry={nodes.Circle007_Material001_0.geometry} material={materials['Material.001']} position={[44.405, 13.063, -233.381]} scale={3.319} />
      <mesh geometry={nodes.Cube_Material003_0.geometry} material={materials.material_0} position={[0, 18.503, 206]} rotation={[-Math.PI / 2, 0, 0]} scale={[65.861, 2.375, 0.568]} />
      <mesh geometry={nodes.Cube001_Material008_0.geometry} material={materials['Material.008']} position={[36.166, 97.547, -52.398]} rotation={[-Math.PI / 2, 0, 0]} scale={11.531} />
      <mesh geometry={nodes.Cube002_Material008_0.geometry} material={materials['Material.008']} position={[-37.532, 97.547, -52.398]} rotation={[-Math.PI / 2, 0, 0]} scale={11.531} />
      <mesh geometry={nodes.Cube003_Material008_0.geometry} material={materials['Material.008']} position={[46.545, 97.547, -124.107]} rotation={[-Math.PI / 2, 0, 0]} scale={11.531} />
      <mesh geometry={nodes.Cube004_Material003_0.geometry} material={materials.material_0} position={[0, 82.567, 43.26]} rotation={[-Math.PI / 2, 0, 0]} scale={108.495} />
      <mesh geometry={nodes.Kapdepan_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.lampudepan_Material002_0.geometry} material={materials['Material.002']} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane001_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane002_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane003_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane004_Material002_0.geometry} material={materials['Material.002']} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane005_Material006_0.geometry} material={materials['Material.006']} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane006_Material006_0.geometry} material={materials['Material.006']} position={[0, 82.837, 114.902]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane007_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane008_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane011_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane012_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane013_glass_0.geometry} material={materials.glass} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane014_glass_0.geometry} material={materials.glass} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane016_glass_0.geometry} material={materials.glass} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane017_glass_0.geometry} material={materials.glass} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane018_Material006_0.geometry} material={materials['Material.006']} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane019_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane020_Material003_0.geometry} material={materials.material_0} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane021_Material001_0.geometry} material={materials['Material.001']} position={[0, 82.839, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={21.635} />
      <mesh geometry={nodes.Plane022_Material001_0.geometry} material={materials['Material.001']} position={[0, 114.156, 114.78]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.997, 21.635, 21.635]} />
      <mesh geometry={nodes.Text__0.geometry} material={materials.Text__0} position={[6.381, 89.742, -8.885]} scale={18.308} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
